version: '3'
services:
    nginx:
        image: nginx:1.15-alpine
        ports:
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
